/**
 *
 * $Id$
 */
package PNPL.validation;

import PNPL.Node;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link PNPL.Node}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateAbstract(boolean value);
	boolean validateMandatory(boolean value);
	boolean validateExclude(EList<Node> value);
	boolean validateRequires(EList<Node> value);
	boolean validateSelect(boolean value);
}
