/**
 *
 * $Id$
 */
package PNPL.validation;

import PNPL.FeatureModel;
import PNPL.PetriNet;
import PNPL.PresenceCondition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link PNPL.pnpl}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface pnplValidator {
	boolean validate();

	boolean validatePn_150(PetriNet value);
	boolean validateFeaturemodel(FeatureModel value);
	boolean validatePresencecondition(EList<PresenceCondition> value);
}
